### PR TITLE
Readme: Add archival note

### PR DESCRIPTION
**Pull request by jaagut**

### CODE REVIEW

**Comment by jaagut** [comment]
Please archive this repo after merging...

**Comment by Flova** [comment]
The ros sports markers are not interactive (yet) but we can archive this never the less imo..
But they use the soccer vision msgs and are ported to ros2! I don't know if they work tho.

**Comment by jaagut** [comment]
Yes, they are not interactive. But I am not sure, this functionality is even useful, as it's not really possible to test the behavior with it. It's much easier to start a simulation.

**Comment by jaagut** [comment]
@Flova could you please review this?

**Comment by Flova** [comment]
I agree with you that a full sun test ist better most of the time and this reduces also code that needs to be maintained etc.

**Review by Flova — APPROVED** [review]

**Comment by Flova** [comment]
Do we want to flag the repo as archived?

**Pull request merged**
